# Railway TOML Configuration

[env]
PORT = ""
APP_URL = ""
MONGODB_URI = ""
ALLOW_JID = "null"
BLOCK_JID = "null"
DATABASE_URL = ""
TZ = "Asia/Karachi"
TIME_ZONE = "Asia/Karachi"
GITHUB = "https://wa.me/+919737825303"
GURL = "https://wa.me/+919737825303"
THUMB_IMAGE = "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true"
CAPTION = "Powered by ℝ⊙|ｉ┼ん"
SUDO = "null"
OWNER_NUMBER = "919737825303"
STYLE = "1"
FLUSH = "false"
GOODBYE = "false"
WELCOME = "false"
WARN_COUNT = 3
DISABLE_PM = "false"
DISABLE_GROUPS = "false"
MSGS_IN_LOG = "false"
USER_IMAGES = ""
WAPRESENCE = "null"
READ_COMMAND = "false"
READ_MESSAGE = "true"
READ_MESSAGE_FROM = "918128729017,918743966915,919667414383,918130601705"
AUTO_READ_STATUS = "false"
AUTO_SAVE_STATUS = "false"
SAVE_STATUS_FROM = "null"
READ_STATUS_FROM = "null"
SESSION_ID = ""
MENU = "2"
PREFIX = "."
BRANCH = "main"
VERSION = "1.3.7"
PACK_AUTHER = ""
PACK_NAME = ""
BOT_NAME = "Riruru"
OWNER_NAME = "It's Rolith"
ERROR_CHAT = ""
KOYEB_API = "false"
REMOVE_BG_KEY = ""
OPENAI_API_KEY = ""
HEROKU_API_KEY = ""
HEROKU_APP_NAME = ""
ANTILINK_VALUES = "all"
WORKTYPE = "private"
MODE = "private"
THEME = "SUHAIL"
ELEVENLAB_API_KEY = "sk_645517ba6cc5da6efd8216dd8d4592fe295e911d43a43889"
AITTS_ID = "37"
